using System;
using System.Collections.Generic;
using CLG_AccesBD;

class clg_Controleur
{
	public static clg_Connection c_cnx;
	public static SortedList<Int64, object> c_ColObjet = new SortedList<Int64, object>();

	public clg_CTL_PUS_PUITS_STOCKAGE c_CTL_PUS_PUITS_STOCKAGE;
	public clg_CTL_PUT_PUISSANCE_THERMIQUE c_CTL_PUT_PUISSANCE_THERMIQUE;
	public clg_CTL_RAD_RADIO_ELEMENT c_CTL_RAD_RADIO_ELEMENT;
	public clg_CTL_SAISIR c_CTL_SAISIR;
	public clg_CTL_SIE_SITE_EXUTOIRE c_CTL_SIE_SITE_EXUTOIRE;
	public clg_CTL_SORTIR c_CTL_SORTIR;
	public clg_CTL_SPR_SITE_PRODUCTEUR c_CTL_SPR_SITE_PRODUCTEUR;
	public clg_CTL_SQA_SEQUENCE_ACTION c_CTL_SQA_SEQUENCE_ACTION;
	public clg_CTL_SRE_SURREMBALLAGE c_CTL_SRE_SURREMBALLAGE;
	public clg_CTL_TN_TN c_CTL_TN_TN;
	public clg_CTL_TYC_TYPE_CONTROLE c_CTL_TYC_TYPE_CONTROLE;
	public clg_CTL_TYD_TYPE__DECHET c_CTL_TYD_TYPE__DECHET;
	public clg_CTL_TYV_TYPE_VARIABLE c_CTL_TYV_TYPE_VARIABLE;
	public clg_CTL_VER_VERIFICATION_CONTROLE c_CTL_VER_VERIFICATION_CONTROLE;
	public clg_CTL_COMPTEUR c_CTL_COMPTEUR;
	public clg_CTL_ACT_ACTION c_CTL_ACT_ACTION;
	public clg_CTL_AGENT_ICEDA c_CTL_AGENT_ICEDA;
	public clg_CTL_CALER c_CTL_CALER;
	public clg_CTL_CHZ_CHOOZ c_CTL_CHZ_CHOOZ;
	public clg_CTL_CLS_COLIS c_CTL_CLS_COLIS;
	public clg_CTL_COMPOSER_DOCUMENT c_CTL_COMPOSER_DOCUMENT;
	public clg_CTL_COMPOSITION_RADIOELEMENTS c_CTL_COMPOSITION_RADIOELEMENTS;
	public clg_CTL_CONTROLE c_CTL_CONTROLE;
	public clg_CTL_CONTROLER c_CTL_CONTROLER;
	public clg_CTL_CONTROLER_SAISIE c_CTL_CONTROLER_SAISIE;
	public clg_CTL_COULER c_CTL_COULER;
	public clg_CTL_COU_COULIS c_CTL_COU_COULIS;
	public clg_CTL_CRA_CRAYON c_CTL_CRA_CRAYON;
	public clg_CTL_CTA_CONTROLE_ATTENDU c_CTL_CTA_CONTROLE_ATTENDU;
	public clg_CTL_CTR_CONTROLE c_CTL_CTR_CONTROLE;
	public clg_CTL_DCO_DOCUMENT_COULIS c_CTL_DCO_DOCUMENT_COULIS;
	public clg_CTL_DCT_DOCUMENT c_CTL_DCT_DOCUMENT;
	public clg_CTL_DDR_DOCUMENT_DRA c_CTL_DDR_DOCUMENT_DRA;
	public clg_CTL_DEFINIR_TYPE_DECHET c_CTL_DEFINIR_TYPE_DECHET;
	public clg_CTL_DEPLACER c_CTL_DEPLACER;
	public clg_CTL_DSP_DOCUMENT_SPECTRO c_CTL_DSP_DOCUMENT_SPECTRO;
	public clg_CTL_EMI_EMBALLAGE_IP2 c_CTL_EMI_EMBALLAGE_IP2;
	public clg_CTL_EMP_EMPLACEMENT c_CTL_EMP_EMPLACEMENT;
	public clg_CTL_EMT_EMBALLAGE_DE_TRANSPORT c_CTL_EMT_EMBALLAGE_DE_TRANSPORT;
	public clg_CTL_EPS_EMPLACEMENT_PUITS_STOCKAGE c_CTL_EPS_EMPLACEMENT_PUITS_STOCKAGE;
	public clg_CTL_ETU_ETUI c_CTL_ETU_ETUI;
	public clg_CTL_FNC_FICHE_NON_CONFORMITE c_CTL_FNC_FICHE_NON_CONFORMITE;
	public clg_CTL_GROUPER c_CTL_GROUPER;
	public clg_CTL_GROUPER_ACTION c_CTL_GROUPER_ACTION;
	public clg_CTL_HID_HISTORIQUE_DOCUMENT c_CTL_HID_HISTORIQUE_DOCUMENT;
	public clg_CTL_HIE_HISTORIQUE_EMPLACEMENT c_CTL_HIE_HISTORIQUE_EMPLACEMENT;
	public clg_CTL_HIL_HISTORIQUE_LOCAL c_CTL_HIL_HISTORIQUE_LOCAL;
	public clg_CTL_HIM_HISTORIQUE_MOUVEMENT c_CTL_HIM_HISTORIQUE_MOUVEMENT;
	public clg_CTL_HIP_HISTORIQUE_PUISSANCETHERMIQUE c_CTL_HIP_HISTORIQUE_PUISSANCETHERMIQUE;
	public clg_CTL_HISTORISER_PUISSANCETHERMIQUE c_CTL_HISTORISER_PUISSANCETHERMIQUE;
	public clg_CTL_INF_INFORMATION c_CTL_INF_INFORMATION;
	public clg_CTL_LCL_LOCAL c_CTL_LCL_LOCAL;
	public clg_CTL_MUT_MUTUALISATION c_CTL_MUT_MUTUALISATION;
	public clg_CTL_PAN_PANIER c_CTL_PAN_PANIER;
	public clg_CTL_PAR_CARACTERISTIQUE c_CTL_PAR_CARACTERISTIQUE;
	public clg_CTL_PROFIL c_CTL_PROFIL;

	public clg_Controleur(clg_Connection pCnx)
	{
		c_cnx = pCnx;
		CreerCTL();
	}

	private void CreerCTL()
	{
		c_CTL_PUS_PUITS_STOCKAGE = new clg_CTL_PUS_PUITS_STOCKAGE();
		clg_PUS_PUITS_STOCKAGE.c_CTL_PUS_PUITS_STOCKAGE = c_CTL_PUS_PUITS_STOCKAGE;

		c_CTL_PUT_PUISSANCE_THERMIQUE = new clg_CTL_PUT_PUISSANCE_THERMIQUE();
		clg_PUT_PUISSANCE_THERMIQUE.c_CTL_PUT_PUISSANCE_THERMIQUE = c_CTL_PUT_PUISSANCE_THERMIQUE;

		c_CTL_RAD_RADIO_ELEMENT = new clg_CTL_RAD_RADIO_ELEMENT();
		clg_RAD_RADIO_ELEMENT.c_CTL_RAD_RADIO_ELEMENT = c_CTL_RAD_RADIO_ELEMENT;

		c_CTL_SAISIR = new clg_CTL_SAISIR();

		c_CTL_SIE_SITE_EXUTOIRE = new clg_CTL_SIE_SITE_EXUTOIRE();
		clg_SIE_SITE_EXUTOIRE.c_CTL_SIE_SITE_EXUTOIRE = c_CTL_SIE_SITE_EXUTOIRE;

		c_CTL_SORTIR = new clg_CTL_SORTIR();
		clg_SORTIR.c_CTL_SORTIR = c_CTL_SORTIR;

		c_CTL_SPR_SITE_PRODUCTEUR = new clg_CTL_SPR_SITE_PRODUCTEUR();
		clg_SPR_SITE_PRODUCTEUR.c_CTL_SPR_SITE_PRODUCTEUR = c_CTL_SPR_SITE_PRODUCTEUR;

		c_CTL_SQA_SEQUENCE_ACTION = new clg_CTL_SQA_SEQUENCE_ACTION();
		clg_SQA_SEQUENCE_ACTION.c_CTL_SQA_SEQUENCE_ACTION = c_CTL_SQA_SEQUENCE_ACTION;

		c_CTL_SRE_SURREMBALLAGE = new clg_CTL_SRE_SURREMBALLAGE();
		clg_SRE_SURREMBALLAGE.c_CTL_SRE_SURREMBALLAGE = c_CTL_SRE_SURREMBALLAGE;

		c_CTL_TN_TN = new clg_CTL_TN_TN();
		clg_TN_TN.c_CTL_TN_TN = c_CTL_TN_TN;

		c_CTL_TYC_TYPE_CONTROLE = new clg_CTL_TYC_TYPE_CONTROLE();
		clg_TYC_TYPE_CONTROLE.c_CTL_TYC_TYPE_CONTROLE = c_CTL_TYC_TYPE_CONTROLE;

		c_CTL_TYD_TYPE__DECHET = new clg_CTL_TYD_TYPE__DECHET();
		clg_TYD_TYPE__DECHET.c_CTL_TYD_TYPE__DECHET = c_CTL_TYD_TYPE__DECHET;

		c_CTL_TYV_TYPE_VARIABLE = new clg_CTL_TYV_TYPE_VARIABLE();
		clg_TYV_TYPE_VARIABLE.c_CTL_TYV_TYPE_VARIABLE = c_CTL_TYV_TYPE_VARIABLE;

		c_CTL_VER_VERIFICATION_CONTROLE = new clg_CTL_VER_VERIFICATION_CONTROLE();
		clg_VER_VERIFICATION_CONTROLE.c_CTL_VER_VERIFICATION_CONTROLE = c_CTL_VER_VERIFICATION_CONTROLE;

		c_CTL_COMPTEUR = new clg_CTL_COMPTEUR();
		clg_COMPTEUR.c_CTL_COMPTEUR = c_CTL_COMPTEUR;

		c_CTL_ACT_ACTION = new clg_CTL_ACT_ACTION();
		clg_ACT_ACTION.c_CTL_ACT_ACTION = c_CTL_ACT_ACTION;

		c_CTL_AGENT_ICEDA = new clg_CTL_AGENT_ICEDA();
		clg_AGENT_ICEDA.c_CTL_AGENT_ICEDA = c_CTL_AGENT_ICEDA;

		c_CTL_CALER = new clg_CTL_CALER();

		c_CTL_CHZ_CHOOZ = new clg_CTL_CHZ_CHOOZ();
		clg_CHZ_CHOOZ.c_CTL_CHZ_CHOOZ = c_CTL_CHZ_CHOOZ;

		c_CTL_CLS_COLIS = new clg_CTL_CLS_COLIS();
		clg_CLS_COLIS.c_CTL_CLS_COLIS = c_CTL_CLS_COLIS;

		c_CTL_COMPOSER_DOCUMENT = new clg_CTL_COMPOSER_DOCUMENT();

		c_CTL_COMPOSITION_RADIOELEMENTS = new clg_CTL_COMPOSITION_RADIOELEMENTS();

		c_CTL_CONTROLE = new clg_CTL_CONTROLE();

		c_CTL_CONTROLER = new clg_CTL_CONTROLER();

		c_CTL_CONTROLER_SAISIE = new clg_CTL_CONTROLER_SAISIE();

		c_CTL_COULER = new clg_CTL_COULER();

		c_CTL_COU_COULIS = new clg_CTL_COU_COULIS();
		clg_COU_COULIS.c_CTL_COU_COULIS = c_CTL_COU_COULIS;

		c_CTL_CRA_CRAYON = new clg_CTL_CRA_CRAYON();
		clg_CRA_CRAYON.c_CTL_CRA_CRAYON = c_CTL_CRA_CRAYON;

		c_CTL_CTA_CONTROLE_ATTENDU = new clg_CTL_CTA_CONTROLE_ATTENDU();
		clg_CTA_CONTROLE_ATTENDU.c_CTL_CTA_CONTROLE_ATTENDU = c_CTL_CTA_CONTROLE_ATTENDU;

		c_CTL_CTR_CONTROLE = new clg_CTL_CTR_CONTROLE();
		clg_CTR_CONTROLE.c_CTL_CTR_CONTROLE = c_CTL_CTR_CONTROLE;

		c_CTL_DCO_DOCUMENT_COULIS = new clg_CTL_DCO_DOCUMENT_COULIS();
		clg_DCO_DOCUMENT_COULIS.c_CTL_DCO_DOCUMENT_COULIS = c_CTL_DCO_DOCUMENT_COULIS;

		c_CTL_DCT_DOCUMENT = new clg_CTL_DCT_DOCUMENT();
		clg_DCT_DOCUMENT.c_CTL_DCT_DOCUMENT = c_CTL_DCT_DOCUMENT;

		c_CTL_DDR_DOCUMENT_DRA = new clg_CTL_DDR_DOCUMENT_DRA();
		clg_DDR_DOCUMENT_DRA.c_CTL_DDR_DOCUMENT_DRA = c_CTL_DDR_DOCUMENT_DRA;

		c_CTL_DEFINIR_TYPE_DECHET = new clg_CTL_DEFINIR_TYPE_DECHET();

		c_CTL_DEPLACER = new clg_CTL_DEPLACER();
		clg_DEPLACER.c_CTL_DEPLACER = c_CTL_DEPLACER;

		c_CTL_DSP_DOCUMENT_SPECTRO = new clg_CTL_DSP_DOCUMENT_SPECTRO();
		clg_DSP_DOCUMENT_SPECTRO.c_CTL_DSP_DOCUMENT_SPECTRO = c_CTL_DSP_DOCUMENT_SPECTRO;

		c_CTL_EMI_EMBALLAGE_IP2 = new clg_CTL_EMI_EMBALLAGE_IP2();
		clg_EMI_EMBALLAGE_IP2.c_CTL_EMI_EMBALLAGE_IP2 = c_CTL_EMI_EMBALLAGE_IP2;

		c_CTL_EMP_EMPLACEMENT = new clg_CTL_EMP_EMPLACEMENT();
		clg_EMP_EMPLACEMENT.c_CTL_EMP_EMPLACEMENT = c_CTL_EMP_EMPLACEMENT;

		c_CTL_EMT_EMBALLAGE_DE_TRANSPORT = new clg_CTL_EMT_EMBALLAGE_DE_TRANSPORT();
		clg_EMT_EMBALLAGE_DE_TRANSPORT.c_CTL_EMT_EMBALLAGE_DE_TRANSPORT = c_CTL_EMT_EMBALLAGE_DE_TRANSPORT;

		c_CTL_EPS_EMPLACEMENT_PUITS_STOCKAGE = new clg_CTL_EPS_EMPLACEMENT_PUITS_STOCKAGE();
		clg_EPS_EMPLACEMENT_PUITS_STOCKAGE.c_CTL_EPS_EMPLACEMENT_PUITS_STOCKAGE = c_CTL_EPS_EMPLACEMENT_PUITS_STOCKAGE;

		c_CTL_ETU_ETUI = new clg_CTL_ETU_ETUI();
		clg_ETU_ETUI.c_CTL_ETU_ETUI = c_CTL_ETU_ETUI;

		c_CTL_FNC_FICHE_NON_CONFORMITE = new clg_CTL_FNC_FICHE_NON_CONFORMITE();
		clg_FNC_FICHE_NON_CONFORMITE.c_CTL_FNC_FICHE_NON_CONFORMITE = c_CTL_FNC_FICHE_NON_CONFORMITE;

		c_CTL_GROUPER = new clg_CTL_GROUPER();
		clg_GROUPER.c_CTL_GROUPER = c_CTL_GROUPER;

		c_CTL_GROUPER_ACTION = new clg_CTL_GROUPER_ACTION();

		c_CTL_HID_HISTORIQUE_DOCUMENT = new clg_CTL_HID_HISTORIQUE_DOCUMENT();
		clg_HID_HISTORIQUE_DOCUMENT.c_CTL_HID_HISTORIQUE_DOCUMENT = c_CTL_HID_HISTORIQUE_DOCUMENT;

		c_CTL_HIE_HISTORIQUE_EMPLACEMENT = new clg_CTL_HIE_HISTORIQUE_EMPLACEMENT();
		clg_HIE_HISTORIQUE_EMPLACEMENT.c_CTL_HIE_HISTORIQUE_EMPLACEMENT = c_CTL_HIE_HISTORIQUE_EMPLACEMENT;

		c_CTL_HIL_HISTORIQUE_LOCAL = new clg_CTL_HIL_HISTORIQUE_LOCAL();
		clg_HIL_HISTORIQUE_LOCAL.c_CTL_HIL_HISTORIQUE_LOCAL = c_CTL_HIL_HISTORIQUE_LOCAL;

		c_CTL_HIM_HISTORIQUE_MOUVEMENT = new clg_CTL_HIM_HISTORIQUE_MOUVEMENT();
		clg_HIM_HISTORIQUE_MOUVEMENT.c_CTL_HIM_HISTORIQUE_MOUVEMENT = c_CTL_HIM_HISTORIQUE_MOUVEMENT;

		c_CTL_HIP_HISTORIQUE_PUISSANCETHERMIQUE = new clg_CTL_HIP_HISTORIQUE_PUISSANCETHERMIQUE();
		clg_HIP_HISTORIQUE_PUISSANCETHERMIQUE.c_CTL_HIP_HISTORIQUE_PUISSANCETHERMIQUE = c_CTL_HIP_HISTORIQUE_PUISSANCETHERMIQUE;

		c_CTL_HISTORISER_PUISSANCETHERMIQUE = new clg_CTL_HISTORISER_PUISSANCETHERMIQUE();

		c_CTL_INF_INFORMATION = new clg_CTL_INF_INFORMATION();
		clg_INF_INFORMATION.c_CTL_INF_INFORMATION = c_CTL_INF_INFORMATION;

		c_CTL_LCL_LOCAL = new clg_CTL_LCL_LOCAL();
		clg_LCL_LOCAL.c_CTL_LCL_LOCAL = c_CTL_LCL_LOCAL;

		c_CTL_MUT_MUTUALISATION = new clg_CTL_MUT_MUTUALISATION();
		clg_MUT_MUTUALISATION.c_CTL_MUT_MUTUALISATION = c_CTL_MUT_MUTUALISATION;

		c_CTL_PAN_PANIER = new clg_CTL_PAN_PANIER();
		clg_PAN_PANIER.c_CTL_PAN_PANIER = c_CTL_PAN_PANIER;

		c_CTL_PAR_CARACTERISTIQUE = new clg_CTL_PAR_CARACTERISTIQUE();
		clg_PAR_CARACTERISTIQUE.c_CTL_PAR_CARACTERISTIQUE = c_CTL_PAR_CARACTERISTIQUE;

		c_CTL_PROFIL = new clg_CTL_PROFIL();
		clg_PROFIL.c_CTL_PROFIL = c_CTL_PROFIL;

	}
}
